all:
	fpc -Sd ./GeneralizedSuffixTreeTest.lpr -Fu../ -Fu../../../* -Fu../../../*/* -oGeneralizedSuffixTreeTest -FU/tmp

memleak:
	fpc -gh -g -gl -Sd ./GeneralizedSuffixTreeTest.lpr -Fu../ -Fu../../../*/* -Fu../../../* -FU/tmp  -oMLeakGeneralizedSuffixTreeTest

