ValidArgumentsInfo: array of AnsiString =
  (
  '--Debug:Integer',
  '--Pipeline.StepID:Integer',
  '--Pipeline.FromStepID:Integer',
  '--InputFile:AnsiString',
  '--WorkingDir:AnsiString',
  '--DebugIndex:Integer',
  '--DebugStart:Integer',
  '--DebugEnd:Integer',
  '--Mode:AnsiString',
  '--TaskID:Integer');
ValidArgumentsValues: array of AnsiString =
  (
  '0',
  '-1',
  '1',
  '',
  '',
  '-1',
  '-1',
  '-1',
  '',
  '-1');
